name: "Update component version"
description: "Updates the version of a specific component"
inputs:
  deploy_key:
    description: 'Private SSH key. Public key must be added to the destination repostitory as a deploy key with push access'
    required: true
  destination_repo:
    description: 'Git repository to create PR in'
    required: true
  destination_folder:
    description: 'Directory in destination repo'
    required: true
    default: '.'
  destination_branch:
    description: 'Branch in destination repo to push changes to (default `development`)'
    required: false
    default: 'development'
  git_username:
    description: 'Git username'
    required: false
    default: ${{ github.actor }}
  git_email:
    description: 'Git email address'
    required: false
    default: ${{ github.actor }}
  commit_message:
    description: 'Commit message'
    required: false
    default: "${{ github.job }} ..."
outputs:
  commit_hash:
    description: 'The SHA hash of the generated commit'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source }}
    - ${{ inputs.destination_repo }}
    - ${{ inputs.destination_folder }}
    - ${{ inputs.deploy_key }}
    - ${{ inputs.git_username }}
    - ${{ inputs.git_email }}
    - ${{ inputs.commit_message }}
