name: "Update component version"
description: "Updates the version of a specific component"
inputs:
  component_folder:
    description: 'Directory in destination repo for the component that requires a version update'
    required: true
    default: '.'
  component_name:
    description: 'Name of the component which is used to find the yaml file'
    required: true
    default: '.'
  version:
    description: 'The version it should update to'
    required: true
    default: '.'
outputs:
  commit_hash:
    description: 'The SHA hash of the generated commit'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.component_folder }}
    - ${{ inputs.component_name }}
    - ${{ inputs.version }}
